services:
  solar-app:
    build: .
    container_name: solar-app
    environment:
      PV_DATA_URL: ""
      STORAGE_PATH: /app/data/pv_values.json
    ports:
      - "5000:5000"
    volumes:
      - solar-data:/app/data

  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: solar-prometheus
    command:
      - "--cogit nfig.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - solar-app

  grafana:
    image: grafana/grafana:11.2.0
    container_name: solar-grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - prometheus

volumes:
  solar-data:
  grafana-data:
